### ISSUE TITLE
Change "-" into "_" so we don't have to

### ISSUE THREAD

**Issue by project79** [svanlaere/disable_filters#1]
I'm just to lazy for this and this can be done out of github. I just did it with fancy image gallery. 
Less confusion in future for ordinary users.

**Comment by svanlaere** [comment]
I've renamed the repository, yet the -master suffix remains?

**Comment by project79** [comment]
It's always there when you download it as .zip. In the other hand, you can now clone directly without need to rename folder on the fly. At least that part is easier.

Just add in your Readme file a not to remove "-master".

Also, if you wish, you can tag the release in a form of version.

**Comment by svanlaere** [comment]
I'll add the note about removing -master from the directoryname.
Haven't used Github much and its shows :smile:

**Comment by project79** [comment]
No biggie, I know few commands and always search for rest online.
Most things you can do via GUI app.

**Comment by svanlaere** [comment]
Which GUI do you recommend ?

**Comment by project79** [comment]
You have the whole list of GUIs here: http://git-scm.com/downloads/guis

I personally use SourceTree App as it has most features, it's free, has regular updates and and wider support for git like services (Win/Mac). Github for Win/Mac is also good, but haven't used it in a while.
